#!/usr/bin/env python3
"""Generate kitty/theme.conf from the ACTIVE quickshell theme and live-apply it.

The quickshell theme is picked exactly like the shell picks it: base
config.json, deep-merged with config.<hostname>.json (host wins). The resolved
themes/<name>.json holds 9 tokens (background/surface/primary/secondary/accent/
accentHover/accentMuted/text/textDim) -- no full 16-colour ANSI ramp -- so the
STRUCTURAL colours (bg, fg, cursor, selection, tabs, borders, url) are themed
from those tokens, while ANSI 1-6/9-14 use a curated, variant-aware hue set that
stays readable for ls/git. Neutrals (0/7/8/15) come from the theme.

Run with no args to auto-detect; pass a theme name to force one.
"""
import json, os, re, socket, subprocess, sys

HERE = os.path.dirname(os.path.abspath(__file__))

# quickshell config lives next to kitty in ~/.config, or as a repo sibling.
def qs_dir():
    for c in (os.path.expanduser("~/.config/quickshell"),
              os.path.join(HERE, "..", "quickshell")):
        if os.path.isfile(os.path.join(c, "config.json")):
            return os.path.abspath(c)
    sys.exit("sync-theme: no quickshell config.json found")

def load(path):
    with open(path, encoding="utf-8") as f:
        return json.load(f)

def active_theme_name(qs):
    name = load(os.path.join(qs, "config.json")).get("theme", {}).get("name", "Nord")
    host = os.path.join(qs, f"config.{socket.gethostname()}.json")
    if os.path.isfile(host):
        name = load(host).get("theme", {}).get("name", name)
    return name

# curated ANSI hues (the theme JSON has none). bright = index+8.
HUES = {
    "dark":  {"red": ("#ff5c7a", "#ff7a93"), "green": ("#52e0a1", "#78ecc0"),
              "yellow": ("#f0c674", "#ffd98a"), "blue": ("#5aa2f7", "#7cb7ff"),
              "magenta": ("#c58af9", "#d7b0ff"), "cyan": ("#56d3d3", "#7fe7e7")},
    "light": {"red": ("#d7385e", "#c62f52"), "green": ("#2c9d6a", "#238457"),
              "yellow": ("#b7791f", "#9a6410"), "blue": ("#2f6fed", "#2258c9"),
              "magenta": ("#8a3ffb", "#7027d6"), "cyan": ("#128a9c", "#0e7383")},
}

def build(p, variant):
    h = HUES.get(variant, HUES["dark"])
    if variant == "light":
        c0, c8, c7, c15 = p["text"], p["textDim"], p["surface"], p["background"]
    else:
        c0, c8, c7, c15 = p["surface"], p["secondary"], p["text"], p["text"]
    rows = [
        ("foreground",            p["text"]),
        ("background",            p["background"]),
        ("selection_foreground",  p["background"]),
        ("selection_background",  p["accent"]),
        ("cursor",                p["accent"]),
        ("cursor_text_color",     p["background"]),
        ("url_color",             p["accentHover"]),
        ("active_border_color",   p["accent"]),
        ("inactive_border_color", p["surface"]),
        ("bell_border_color",     p["accentHover"]),
        ("active_tab_foreground", p["background"]),
        ("active_tab_background", p["accent"]),
        ("inactive_tab_foreground", p["textDim"]),
        ("inactive_tab_background", p["surface"]),
        ("tab_bar_background",    p["background"]),
        ("mark1_foreground",      p["background"]),
        ("mark1_background",      p["accent"]),
        ("color0", c0), ("color8", c8),
        ("color1", h["red"][0]),     ("color9",  h["red"][1]),
        ("color2", h["green"][0]),   ("color10", h["green"][1]),
        ("color3", h["yellow"][0]),  ("color11", h["yellow"][1]),
        ("color4", h["blue"][0]),    ("color12", h["blue"][1]),
        ("color5", h["magenta"][0]), ("color13", h["magenta"][1]),
        ("color6", h["cyan"][0]),    ("color14", h["cyan"][1]),
        ("color7", c7), ("color15", c15),
    ]
    w = max(len(k) for k, _ in rows)
    return "\n".join(f"{k.ljust(w)}  {v}" for k, v in rows)

def main():
    qs = qs_dir()
    name = sys.argv[1] if len(sys.argv) > 1 and sys.argv[1] else active_theme_name(qs)
    p = load(os.path.join(qs, "themes", f"{name}.json"))
    body = build(p, p.get("variant", "dark"))
    out = os.path.join(HERE, "theme.conf")
    with open(out, "w", encoding="utf-8") as f:
        f.write(f"# generated by sync-theme.py from quickshell theme: {name}\n"
                "# do not edit by hand -- rerun sync-theme.py\n\n" + body + "\n")
    print(f"sync-theme: wrote {out} <- {name}")
    # best-effort live apply to every running kitty. kitty appends -<pid> to the
    # listen_on abstract socket (@mykitty -> @mykitty-1234), so enumerate them.
    for sock in kitty_sockets():
        try:
            subprocess.run(["kitty", "@", "--to", "unix:" + sock,
                            "set-colors", "--all", "--configured", out],
                           check=False, timeout=5,
                           stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        except (FileNotFoundError, subprocess.SubprocessError):
            pass

def kitty_sockets():
    socks = set()
    try:
        with open("/proc/net/unix") as f:
            for line in f:
                socks.update(re.findall(r"@mykitty-\d+", line))
    except OSError:
        pass
    return sorted(socks)

if __name__ == "__main__":
    main()
