#!/usr/bin/env python3
"""Generate ~/.config/gtk-3.0/gtk.css and ~/.config/gtk-4.0/gtk.css from the active quickshell theme.

Overrides libadwaita's named colours so GTK3/GTK4/libadwaita apps (Nautilus, etc.)
take the quickshell palette.

libadwaita parses gtk.css exactly ONCE, at process startup -- no gsettings/portal
signal makes a running app re-read it (verified: color-scheme toggle, gtk-theme
toggle and file rename all leave a running Nautilus unchanged). Worse, file-manager
apps run as a single-instance GApplication daemon, so closing the window keeps the
process alive and the *next* window reuses the old palette. That's the "only after
a few restarts / after a break" symptom: the daemon has to actually exit before a
new launch picks up the colours. So after writing the files we quit those daemons
(see restart_gtk_apps); the user's next launch starts fresh with the new palette.
The light/dark *variant* still switches live via theme-variant.sh.

Resolves the theme the way the shell does: config.json deep-merged with the host
file, then the theme JSON. Run on theme commit; optional arg forces a theme name.
"""
import json
import os
import socket
import subprocess
import sys

HOME = os.path.expanduser("~")


def qs_dir():
    here = os.path.dirname(os.path.abspath(__file__))
    for c in (os.path.join(HOME, ".config/quickshell"),
              os.path.join(here, "..", "..", "quickshell")):
        if os.path.isfile(os.path.join(c, "config.json")):
            return os.path.abspath(c)
    sys.exit("gtk-palette: no quickshell config.json found")


def load(p):
    with open(p, encoding="utf-8") as f:
        return json.load(f)


def active_name(qs):
    name = load(os.path.join(qs, "config.json")).get(
        "theme", {}).get("name", "Nord")
    host = os.path.join(qs, f"config.{socket.gethostname()}.json")
    if os.path.isfile(host):
        name = load(host).get("theme", {}).get("name", name)
    return name


# libadwaita named colour  <-  quickshell palette token
MAP = {
    "accent_color":              "accent",
    "accent_bg_color":           "accent",
    "accent_fg_color":           "background",
    "window_bg_color":           "background",
    "window_fg_color":           "text",
    "view_bg_color":             "background",
    "view_fg_color":             "text",
    "headerbar_bg_color":        "surface",
    "headerbar_fg_color":        "text",
    "headerbar_backdrop_color":  "background",
    "sidebar_bg_color":          "surface",
    "sidebar_fg_color":          "text",
    "sidebar_backdrop_color":    "background",
    "secondary_sidebar_bg_color": "surface",
    "secondary_sidebar_fg_color": "text",
    "card_bg_color":             "surface",
    "card_fg_color":             "text",
    "popover_bg_color":          "surface",
    "popover_fg_color":          "text",
    "dialog_bg_color":           "surface",
    "dialog_fg_color":           "text",
}

# Running GApplication daemons that must be quit so their next launch re-reads
# gtk.css. Only list apps that (a) linger as a single-instance daemon and
# (b) hold no unsaved state -- quitting them just closes idle windows.
# (process name, quit command). Add more here as needed.
GTK_APPS = [
    ("nautilus", ["nautilus", "-q"]),        # GApplication daemon: graceful quit
    ("hyprmod", ["pkill", "-x", "hyprmod"]),  # no -q flag, so kill the process
]


def restart_gtk_apps():
    for proc_name, quit_cmd in GTK_APPS:
        running = subprocess.run(
            ["pgrep", "-x", proc_name],
            stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
        ).returncode == 0
        if running:
            subprocess.run(quit_cmd, stdout=subprocess.DEVNULL,
                           stderr=subprocess.DEVNULL, check=False)


def write_gtk_css(gtk_version, lines):
    """Write gtk.css for the given GTK major version."""
    out_dir = os.path.join(HOME, f".config/gtk-{gtk_version}.0")
    os.makedirs(out_dir, exist_ok=True)
    css_path = os.path.join(out_dir, "gtk.css")
    with open(css_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    return css_path


def main():
    qs = qs_dir()
    name = sys.argv[1] if len(
        sys.argv) > 1 and sys.argv[1] else active_name(qs)
    p = load(os.path.join(qs, "themes", f"{name}.json"))
    w = max(len(k) for k in MAP)

    lines = [
        f"/* generated by gtk-palette.py from quickshell theme: {name} */"]
    lines += [f"@define-color {named.ljust(w)} {p[tok]};" for named,
              tok in MAP.items()]

    css_gtk3 = write_gtk_css(3, lines)
    css_gtk4 = write_gtk_css(4, lines)
    restart_gtk_apps()

    print(f"gtk-palette: wrote {css_gtk3} <- {name}")
    print(f"gtk-palette: wrote {css_gtk4} <- {name}")


if __name__ == "__main__":
    main()
