#!/usr/bin/env python3
"""Generate hyprlock-colors.conf from the ACTIVE quickshell theme.

Mirrors kitty/sync-theme.py's theme resolution (base config.json deep-merged
with config.<hostname>.json, host wins). hyprlock.conf `source`s the
generated file and references its $-variables, so only the palette changes
here -- layout/sizing/fonts stay hand-authored in hyprlock.conf. No live-apply
step: hyprlock isn't a running daemon, it reads its config fresh each lock.

Run with no args to auto-detect; pass a theme name to force one.
"""
import json, os, socket, sys

HERE = os.path.dirname(os.path.abspath(__file__))
HYPR_DIR = os.path.dirname(HERE)


def qs_dir():
    for c in (os.path.expanduser("~/.config/quickshell"),
              os.path.join(HYPR_DIR, "..", "quickshell")):
        if os.path.isfile(os.path.join(c, "config.json")):
            return os.path.abspath(c)
    sys.exit("sync-hyprlock-theme: no quickshell config.json found")


def load(path):
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def active_theme_name(qs):
    name = load(os.path.join(qs, "config.json")).get("theme", {}).get("name", "Nord")
    host = os.path.join(qs, f"config.{socket.gethostname()}.json")
    if os.path.isfile(host):
        name = load(host).get("theme", {}).get("name", name)
    return name


def hex_to_rgb_triplet(h):
    h = h.lstrip("#")
    return ", ".join(str(int(h[i:i + 2], 16)) for i in (0, 2, 4))


def build(p):
    rows = []
    for token in ("text", "textDim", "background", "surface", "accent"):
        hexval = p[token].lstrip("#")
        rows.append((token, hex_to_rgb_triplet(hexval)))
        rows.append((f"{token}Hex", hexval))
    w = max(len(k) for k, _ in rows)
    return "\n".join(f"${k.ljust(w)} = {v}" for k, v in rows)


def main():
    qs = qs_dir()
    name = sys.argv[1] if len(sys.argv) > 1 and sys.argv[1] else active_theme_name(qs)
    p = load(os.path.join(qs, "themes", f"{name}.json"))
    body = build(p)
    out = os.path.join(HYPR_DIR, "hyprlock-colors.conf")
    with open(out, "w", encoding="utf-8") as f:
        f.write(f"# generated by sync-hyprlock-theme.py from quickshell theme: {name}\n"
                "# do not edit by hand -- rerun sync-hyprlock-theme.py\n\n" + body + "\n")
    print(f"sync-hyprlock-theme: wrote {out} <- {name}")


if __name__ == "__main__":
    main()
